### ISSUE TITLE
You are not whitelisted to use this bridge.

### ISSUE THREAD

**Issue by Thatoo** [YunoHost-Apps/mautrix_signal_ynh#58]
### Describe the bug

After joining the room, the bot leave immediately saying
```
You are not whitelisted to use this bridge.

If you are the owner of this bridge, see the bridge.permissions section in your config file.
```

### Context

- Hardware: Old laptop
- YunoHost version: 11.0.9.15
- I have access to my server: Through SSH | through the webadmin | direct access via keyboard / screen 

### Steps to reproduce

- You invite the bot @telegrambot:yoursynapse.domain
- The bot join and leave immediately saying
```
You are not whitelisted to use this bridge.

If you are the owner of this bridge, see the bridge.permissions section in your config file.
```

### Expected behavior

The bot should accept the invitation and remain in the room

### Other information

In /opt/yunohost/mautrix_telegram/config.yaml, the `bridge.permissions` are as follow : 
```
 # Homeserver details
 homeserver:
     # The address that this appservice can use to connect to the homeserver.
     address: https://matrix.MYDOMAIN.fr
     # The domain of the homeserver (for MXIDs, etc).
     domain: MYDOMAIN.fr


     # Permissions for using the bridge.
     # Permitted values:
     #      relay - Allowed to be relayed through the bridge, no access to commands.
     #       user - Use the bridge with puppeting.
     #      admin - Use and administrate the bridge.
     # Permitted keys:
     #        * - All Matrix users
     #   domain - All users on that homeserver
     #     mxid - Specific user
     permissions:
         '*': relay
         domain: user
         xxxx@MYDOMAIN.fr: admin
```

and the user inviting the bot is thatoo@MYDOMAIN.fr so it is one of the user on that homeserver.

Any idea what I can do to solve my issue?
