### ISSUE TITLE
Build signald from source

### ISSUE THREAD

**Issue by Gredin67** [YunoHost-Apps/mautrix_signal_ynh#9]
### Describe the bug

- bridge communication with signald is failing #5 #8 

### Steps to reproduce
Install or remove and re-install the bridge.

### Solution
- install signald from source
- create signald user and service using yunohost helpers
- set signald and mautrix_signal user permissions properly
- set signald and mautrix folders access rights properly

**Comment by centralscrutinizer21** [comment]
Thanks @Gredin67 so a solution does exists.
Would you mind helping me with the above steps?

> install signald from source
I installed it following [this](https://signald.org/articles/install/source/)  guide.
I am still not sure in wich path I should be when downloading building and configuring signald though.
> create signald user and service using yunohost helpers
I was reading [this](https://yunohost.org/it/packaging_apps_helpers?q=%2Fpackaging_apps_helpers) to understand what helpers are about, but I don't understand if they are to be used only when packaging apps or also as configurators after installation. In the second case which helpers should I use to create signald user and service?

> third and

> fourth point 
I think here you are talking about basic linux commands (chown chmod)? If so can you please define properly? :)

Thanks again

**Comment by Gredin67** [comment]
I started something on the testing branch 
https://github.com/YunoHost-Apps/mautrix_signal_ynh/commit/446d4208157d452cd76e61d072117dbbcd02292b

Le 2021-08-06 15:45, centralscrutinizer21 a écrit :

**Comment by Thatoo** [comment]
Will this make mautrix signal bridge on yunohost OK for production @Gredin67 ?

**Comment by MayeulC** [comment]
Compile-time dependencies identified: `javahelper default-jdk-headless`

As per [the instructions](https://signald.org/articles/install/source/):
```sh
git clone https://gitlab.com/signald/signald.git
cd signald
make installDist
make deb
# Result is in ../signald_0.23.0-1-476a9a37_all.deb
```

It was relatively quick for me, but not everybody has a 8-core Xeon and Gigabit Internet connection.

Here's the build script from upstream's CI, which is substantially the same thing as the Makefile does. By default, Architecture is set to "All", which shouldn't be an issue.
```yaml
  before_script:
    - export VERSION="$(./version.sh)"
    - echo "Building signald version $VERSION"
    - "sed -i 's/^Architecture:.*/Architecture: amd64/g' debian/control"
  script:
    - gbp dch --ignore-branch --debian-tag="%(version)s" --git-author --new-version="${VERSION}"
    - dpkg-buildpackage -b
    - mv ../signald_* .
  artifacts:
    paths:
      - "signald_*"
```

Maybe we can let the user choose to compile it at install time... I wish we were on Guix and could just provide the compile script and binary substitutes servers would handle the rest x)
